### ISSUE TITLE
Format Xls tidak terbaca

### ISSUE THREAD

**Issue by dodoizm** [rrifafauzikomara/Apriori-and-AssociationRule-WebBased#1]
Selamat siang, 

saya sudah mendownload source-code-nya dan sudah menjalankan semua script²nya, tapi di file yang anda kasih ada file yang kurang, yaitu database file-nya (.sql). 

dan yang kedua, ketika saya coba di demo site yang link-nya anda sediakan, saya mencoba untuk mengupload file .xls-nya, tapi data tidak terbaca.

mohon solusinya, terima kasih

**Comment by rrifafauzikomara** [comment]
@dodoizm 

1. Untuk dbnya saya jual
2. Untuk format xmlnya harus sama percis dengan yang ada di dalam sini: https://github.com/rrifafauzikomara/Apriori-and-AssociationRule-WebBased/tree/master/Format
